version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    docker:
      - image: circleci/node:10
      - image: circleci/postgres:10
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circleci
    environment:
      TEST_DATABASE: circleci
      POSTGRES_USER: circleci
      POSTGRES_DB: circleci
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test